[package]
name = "howmanysmall/typed-profile-service"
description = "A typed version of ProfileService!"
version = "1.0.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	".vscode",
	".gitignore",
	"scripts",
	".luaurc",
	"place.project.json",
	"roblox.yml",
	"rokit.toml",
	"selene.toml",
	"stylua.toml",
	"TypedProfileService.code-workspace",
]

[dependencies]
Janitor = "howmanysmall/janitor@1.16.0"
Promise = "howmanysmall/typed-promise@4.0.3"
